CREATE DATABASE  magicbanck;

-- 1
CREATE TABLE states {
    id SERIAL NOT NULL PRIMARY KEY,
	name TEXT NOT NULL  UNIQUE
};
--2

CREATE TABLE cities {
 id SERIAL NOT NULL PRIMARY KEY
 name TEXT NOT NULL
 "stateId" INTEGER REFERENCES states(id)
};